### ISSUE TITLE
Recover schema axioms from ACSet type

### ISSUE THREAD

**Issue by epatters** [AlgebraicJulia/ACSets.jl#10]
The ACSet system converts finitely presented schemas into Julia types. However, it omits the equational axioms, which means that the presentation cannot be completely recovered from the type. This has been brought out by @slibkind's PR AlgebraicJulia/Catlab.jl#433, which defines a `Presentation` constructor for ACSet types that cannot recover the axioms.

We should provide some mechanism to completely recover the schema from the ACSet type. We could probably do this by encoding the axioms as pairs of tuples in the type parameters.

I think this will become important as we incorporate equational reasoning about schemas, e.g., in a hypothetical improved algorithm for left pushforward data migration (#436). Consider that the schemas for reflexive or symmetric graphs are not just finitely presented, but actually finite—however, you can only know this if you have the axioms!

**Comment by kris-brown** [comment]
this should also be addressed https://github.com/AlgebraicJulia/ACSets.jl/issues/18
