### ISSUE TITLE
Java Support for InterTypes

### ISSUE THREAD

**Issue by fivegrant** [AlgebraicJulia/ACSets.jl#107]
[Terarium](https://github.com/DARPA-ASKEM/terarium) relies on the InterTypes that generate the [ASKEM Model Representation](https://github.com/DARPA-ASKEM/Model-Representations) for Decapodes.

Since the backend is written in Java, InterTypes needs to support this language as well.

@mwdchang @kbirk Will plain Java classes be enough here or does Spring Boot require something else?

**Comment by kbirk** [comment]
Plain java classes should be fine :)

**Comment by jpfairbanks** [comment]
Can you auto-generate them from the JSON Schema?

**Comment by olynch** [comment]
It's probably a better idea to support Java directly; the JSON Schema doesn't contain everything needed.

**Comment by YohannParis** [comment]
> Can you auto-generate them from the JSON Schema?

We cannot do. See: https://askemgroup.slack.com/archives/C03THCGK2DU/p1706729235838829
