### ISSUE TITLE
Constructor for StructACSet that accepts a DynamicACSet

### ISSUE THREAD

**Issue by aaguinal** [AlgebraicJulia/ACSets.jl#122]

**Comment by kris-brown** [comment]
This seems like it should be doable by creating an `AnonACSet` fed a schema from `acset_schema(my_dynamic_acset)` - I'll work on a function that does this! Not sure right now what the name of the function should be (nor the inverse which dynamic-ifies a StructAcset), or if it should just be `StructACSet`

**Comment by epatters** [comment]
Another interpretation of this feature request is creating a struct acset with a fixed schema (whose type already exists) from a dynamic acsets, where it is assumed and checked at runtime that the dynamic acset has the same schema. @aaguinal, can you clarify?

**Comment by aaguinal** [comment]
Sorry if that was confusing. I was hoping the interface would be able to do something like this--

```
g = DynamicACSet("Graph", SchGraph)
add_parts!(g, :V, 4)

new_g = StructACSet(g)  # | to_struct!(g) | something else
@test has_part(new_g, :V, 4)
```

where I've already instantiated an ACSet dynamically with data and I want to cast it to a StructACSet an retain the data.

For my purposes, this is to circumvent the issue reported here https://github.com/AlgebraicJulia/DataMigrations.jl/issues/158
However, I can imagine there might be other use cases.
