### ISSUE TITLE
Generation of acsets from input JSON

### ISSUE THREAD

**Issue by slwu89** [AlgebraicJulia/ACSets.jl#125]
When parsing large amounts of JSON data (e.g. from HTTP queries) it could be useful to automatically generate acsets from query output for easier processing (when we do not yet know the schema; it would also be generated from the input JSON). See the JSON3 package's docs on generated types, and consider how to adapt this to the acset case https://quinnj.github.io/JSON3.jl/stable/#Generated-Types

**Comment by slwu89** [comment]
This rabbit hole goes deeper than I thought, see: https://tomasp.net/academic/papers/fsharp-data/fsharp-data.pdf

**Comment by jpfairbanks** [comment]
TFW you say "it would be nice if my programming language know more about structured data" and rediscover LINQ.

**Comment by slwu89** [comment]
I will close this, because I don't plan to spend time on it. If anyone thinks it should be reopened, please do so.
