### ISSUE TITLE
API Reference page not loading 

### ISSUE THREAD

**Issue by lukem12345** [AlgebraicJulia/ACSets.jl#139]
The API Reference page in these docs is not loading: https://algebraicjulia.github.io/ACSets.jl/dev/api/

Looking at the [corresponding .md file](https://github.com/AlgebraicJulia/ACSets.jl/blob/main/docs/src/api.md), this could probably be resolved by listing out the modules manually, instead of relying on Reexport to pass those docstrings to the main ACSets module.

**Comment by jpfairbanks** [comment]
That is the standard way to resolve this problem. I did it in Gatlab.jl in https://github.com/AlgebraicJulia/GATlab.jl/pull/31/files

**Comment by lukem12345** [comment]
My initial pass at listing out the modules manually uncovered a couple of small errors, such as an invalid do string Ref to `IDAllocator` which was merged with another type and renamed in 26c7530 and a sister commit. I’ll make a pass at updating those sorts of things as well.
