### ISSUE TITLE
Missing docs on github actions

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/ACSets.jl#148]
When you build the docs locally, all of the API docs show up in the right place (ACSets.jl/docs/build/api/index.html). But on Github actions, they are missing. This has actually been broken the whole time. But I can't see how the CI would be building it differently than running docs/make.jl locally.

**Comment by lukem12345** [comment]
https://github.com/AlgebraicJulia/DataMigrations.jl needs the same treatment, and possibly an explicit listing of submodules a la https://github.com/AlgebraicJulia/ACSets.jl/issues/139
