### ISSUE TITLE
Modelling multivalued attributes and collection types

### ISSUE THREAD

**Issue by mhlr** [AlgebraicJulia/ACSets.jl#34]
What is the recommended way of handling multivalued associations like steps in paths,
particularly when the multivalued attributes are ordered or indexed somehow (set, sequence or mapping valued functions in programming languages)?

Are there extension packages that help with this?

Spans can model general muany-many relations, but how can you captre that you are dealing with a sequence valued function? (ie there is a preferred direction and the returned values are ordered, and possibly indexed)

Thanks
Daniel

**Comment by mhlr** [comment]
Thanks @jpfairbanks I was not aware that parametrized collection types were supported. That works for me.

**Comment by epatters** [comment]
Yep, you can use arbitrary Julia types as attribute types. If that works for you, I'll go ahead and close this issue.
