### ISSUE TITLE
No methods for `subpart_type`

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/ACSets.jl#35]
It looks like the ACSet Interface defines `subpart_type` but then the implementation doesn't provide any methods for it. Is that intended to be implemented by users?

**Comment by olynch** [comment]
No, this should be implemented. This would be a #goodfirstissue for a UF grad student, maybe also solving #37 in the process!

**Comment by slwu89** [comment]
Just browsing issues; looks like this one can be closed due to https://github.com/AlgebraicJulia/ACSets.jl/pull/103?

**Comment by epatters** [comment]
Thanks for noticing!
