### ISSUE TITLE
Extend JSON3 write method for ACSets

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/ACSets.jl#78]
We should add 

```julia
using JSON3
JSON3.write(io, acs::ACSet; kwargs...) = JSON3.write(io, generate_json_acset(acs); kwargs...)
```

so that JSON3.write just works for ACSets. The extra level of indirection is useless for most users who aren't debugging serialization code.

**Comment by quffaro** [comment]
I've created [PR #79](https://github.com/AlgebraicJulia/ACSets.jl/pull/79) to add this enhancement.
